 SHOW PROCEDURE STATUS WHERE db = 'ORG';  
 
 /* 
	STORE PROCEDURE FOR
		*Write an SQL query to print details of the Workers who are also Managers*
*/
DROP PROCEDURE IF EXISTS GETMANAGER;
DELIMITER //
CREATE PROCEDURE GETMANAGER()
BEGIN
SELECT DISTINCT W.FIRST_NAME, T.WORKER_TITLE
FROM Worker W
INNER JOIN Title T
ON W.WORKER_ID = T.WORKER_REF_ID
AND T.WORKER_TITLE in ('Manager');
END //
DELIMITER ;

/* CALLING A STORED PROCEDURE*/
CALL  GETMANAGER();
 