/*
 CREATING A  STORED FUNCTION FOR FINDING THE NUMBER OF YEARS FROM DOJ OF A WORKER
*/

DELIMITER //
CREATE FUNCTION GETYEARS ( JOINING_DATE datetime) RETURNS INT DETERMINISTIC
BEGIN
DECLARE TEMPDATE DATETIME;
SELECT current_timestamp() INTO TEMPDATE;
RETURN YEAR(TEMPDATE)-YEAR(JOINING_DATE);
END //
DELIMITER ;

/* CALLING THE STORED FUNCTION*/
SELECT FIRST_NAME, LAST_NAME , GETYEARS( JOINING_DATE) AS YEARS_IN_ORG FROM Worker;

/*
 CREATING A  STORED FUNCTION FOR FOR ROUNDING OFF THE SALARY OF A WORKER
*/


DELIMITER //
CREATE FUNCTION ROUNDSALARY(SALARY INT) RETURNS INT DETERMINISTIC
 BEGIN 
 RETURN ROUND(SALARY, -2); 
 END //
 DELIMITER ;
 
 SELECT  FIRST_NAME, LAST_NAME , ROUNDSALARY(SALARY) FROM Worker ;

