USE ORG;

CREATE TABLE NUMBERS (IND INT (15) );
INSERT INTO NUMBERS (IND) values 
(1),
(2),
(3),
(4),
(5),
(6),
(7),
(8),
(9),
(10);

SELECT * FROM NUMBERS


DELIMITER //
CREATE PROCEDURE MULTIPLICATION (IN NUM INT)
BEGIN
DECLARE N VARCHAR(255);
DECLARE FINISHED INTEGER DEFAULT 0;
	/* DECLARE CURSOR*/
	DECLARE MUL CURSOR FOR
    SELECT * FROM NUMBERS;
    
    DECLARE continue HANDLER FOR NOT FOUND SET FINISHED = 1 ;
    
    OPEN MUL;
    
    MULT: LOOP
		FETCH MUL INTO N;
        IF FINISHED = 1 THEN
			LEAVE MULT;
		END IF ;
        SET N = concat(N," ",MULT) ;
	END LOOP MULT;
    CLOSE MUL ;
END //
DELIMITER ;

DROP PROCEDURE MULTIPLICATION;

CALL MULTIPLICATION(2);