DELIMITER &&
DELIMITER &&
CREATE TRIGGER ADD_BONUS 
AFTER
INSERT ON worker
FOR EACH ROW
BEGIN
INSERT INTO bonus(WORKER_REF_ID,BONUS_AMOUNT,BONUS_DATE)
VALUES (NEW.WORKER_ID, 500,NEW.JOINING_DATE);
END ;
&&
DELIMITER ;

drop trigger ADD_BONUS