CREATE VIEW WORKERDETAILS
AS
SELECT W.WORKER_ID, CONCAT(W.FIRST_NAME, ' ' , W.LAST_NAME) AS NAME, W.SALARY, W.JOINING_DATE, W.DEPARTMENT, T.WORKER_TITLE, T.AFFECTED_FROM
FROM WORKER W LEFT JOIN TITLE T
ON W.WORKER_ID = T.WORKER_REF_ID;

SELECT * FROM WORKERDETAILS;

DROP VIEW WORKERDETAILS